### PR TITLE
Move version info from accept/contet-type parameter to mimetype

### PR DESCRIPTION
**Pull request by jasonpaige**
Spring doesn't have adequate support for content negitation with
parameters. Not applying this change will result in lots of
effort to work around the issue until better support is released
by Spring.

### CODE REVIEW

**Comment by kolektiv** [comment]
So, the change you've made there would be out of date, and would need a section on an extra header? (Just checking i've understood). What would it require to make Spring work properly?

**Comment by calinmarina** [comment]
in my opinion the cleanest way would be to add version parameter knowledge for Accept header in
[MediaType](https://github.com/spring-projects/spring-framework/blob/master/spring-web/src/main/java/org/springframework/http/MediaType.java) class... this means helping spring support the issue natively instead of working around it


model is already there, parameters including version are already parsed but there is no special getter/setter for version. Existing comparators with their helpers are exactly what should be added, of course coding around 'version' param. see: [QUALITY_VALUE_COMPARATOR](https://github.com/spring-projects/spring-framework/blob/master/spring-web/src/main/java/org/springframework/http/MediaType.java#LC673), [SPECIFICITY_COMPARATOR](https://github.com/spring-projects/spring-framework/blob/master/spring-web/src/main/java/org/springframework/http/MediaType.java#LC711)

**Comment by jasonpaige** [comment]
Those spring framework looks all seem very tightly coupled to the quality parameter though where as we are looking specifically at the version parameter if we don't want to accept this PR. 

Are we saying we'll need to somehow extend the `MediaType` class and inject it for use in the dispatcher process of Spring? (going way out of my depth in terms of spring knowledge, just assuming it works like most other web MVC frameworks)

**Comment by calinmarina** [comment]
I've tried the MediaType extension but didn't manage to inject it as I haven't found a way to do it... all objects using MediaType are created by factories that have MediaType hadcoded, I haven't found any factory that lets us inject custom ones that's why I think the only way to have it is to add version handling along the quality and type handling, in spring's libraries directly.

I can only see two reasons why they haven't spent time on adding this in Spring:
1. They either don't like the ```Accept: type+json;version=x.x.x``` way thus leaving ```Accept: type.version+json```
2. or, because version as mime type parameter is more or less newer approach in the industry they just got used with previous implemented ways so they haven't spent time on implementing it.

**Comment by KarolJastrzebski** [comment]
@calinmarina Some explanation can be found in the bug reports related to handling content negotiation with media type parameters: [SPR-13365](https://jira.spring.io/browse/SPR-13365) and [SPR-10903](https://jira.spring.io/browse/SPR-10903).

**Comment by rkondratowicz** [comment]
This did not update the guide. html files need to be regenerated.

**Comment by jasonpaige** [comment]
that's annoying. I just tried to run the `./build.sh` script and it just removed `docs/index.hml` :(

**Comment by rkondratowicz** [comment]
same for me

**Comment by kolektiv** [comment]
Well, it worked before...

**Comment by kolektiv** [comment]
What actually changed? It should have removed `/docs` and recreated it - what's in `/docs` after you run `build.sh`

**Comment by jasonpaige** [comment]
it's empty

**Comment by jasonpaige** [comment]
found the problem. the generated html is a bit whack so im fixing up in a branch now

**Comment by jasonpaige** [comment]
my slack is busted but here is the PR: https://github.com/hmcts/restful-api-standards/pull/2

**Pull request merged**
